server:
  port: 9091

  application:
    name: PAYMENT-SERVICESS
    eureka:
    client:
      register-with-client: true
      featch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka
        instance:
          hostname: localhost

