spring :
  application:
    cloud:
      gateway:
        routes:
          - id: order-servise
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/order/**
                filters:
                    - name: CircuitBreaker
                      args:
                        name: order-service
                        fallbackuri: forward:/orderFallBack



              - id: payment-service
              - uri: ib://PAYMENT-SERVICE
                predicates:
                  -Path=/payment/**

filters:
  - name: CircuitBreaker
    args:
      name: payment-service
      fallbackuri: forward:/paymentFallBack


        application:
          name: ORDER-SERVICESS
          eureka:
          client:
            register-with-client: true
            featch-registry: true
            service-url:
              defaultZone: http://localhost:8761/eureka
              instance:
                hostname: localhost